$content = Get-Content src/components/payroll/attendance-dashboard.jsx
$startLine = 809 - 1
$endLine = 1028 - 1 - 1

$before = $content[0..($startLine - 1)]
$after = $content[($endLine + 1)..($content.Length - 1)]

$newLines = @(
'        {/* Simple Text Header matching Image 2 */}',
'        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 mb-8">',
'          <div className="space-y-1">',
'            <h1 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight">',
'              {(viewMode === "monthly" || viewMode === "weekly") ? (',
'                viewMode === "monthly" ? (',
'                  <>Monthly Attendance - {months.find((m) => m.value === selectedMonth)?.label} {selectedYear}</>',
'                ) : (',
'                  <>Weekly Attendance - {(() => {',
'                        const curr = new Date(selectedDate);',
'                        const day = curr.getDay();',
'                        const diff = curr.getDate() - day + (day === 0 ? -6 : 1);',
'                        const start = new Date(curr.setDate(diff));',
'                        const end = new Date(curr.setDate(diff + 6));',
'                        return `${start.toLocaleDateString(''en-US'', { month: ''short'', day: ''numeric'' })} - ${end.toLocaleDateString(''en-US'', { month: ''short'', day: ''numeric'', year: ''numeric'' })}`;',
'                    })()}</>',
'                )',
'              ) : (',
'                isAdminView ? "Attendance Management" : "My Attendance Dashboard"',
'              )}',
'            </h1>',
'            <p className="text-slate-500 text-sm">',
'              {isAdminView ',
'                ? "Track and manage employee attendance records, handle status corrections, and export complete statutory logs." ',
'                : "View clock-in schedules, analyze monthly hours, and submit regularization requests instantly."',
'              }',
'            </p>',
'          </div>',
'',
'          <div className="flex flex-wrap gap-3">',
'            <button',
'              onClick={() =>',
'                router.push(isEmployeeView ? "/employee/attendance/add-attendance" : "/admin/attendance/add-attendance")',
'              }',
'              className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-medium text-sm px-4 py-2.5 rounded-lg transition-colors"',
'            >',
'              <Plus className="w-4 h-4" /> Add Attendance Record',
'            </button>',
'          </div>',
'        </div>',
'',
'        {/* Mark Attendance Section (Visible only for employees) */}',
'        {!isAdminView && (',
'          <div className="mb-8">',
'            <MarkAttendance onAttendanceMarked={fetchAttendance} />',
'          </div>',
'        )}',
'',
'        {/* Professional Filters (Only for Daily View) */}',
'        {viewMode === "daily" && (',
'        <AttendanceFilters ',
'          searchTerm={searchTerm}',
'          setSearchTerm={setSearchTerm}',
'          selectedOrganization={selectedOrganization}',
'          setSelectedOrganization={setSelectedOrganization}',
'          organizations={organizations}',
'          viewMode={viewMode}',
'          selectedDate={selectedDate}',
'          setSelectedDate={setSelectedDate}',
'          selectedMonth={selectedMonth}',
'          setSelectedMonth={setSelectedMonth}',
'          selectedYear={selectedYear}',
'          setSelectedYear={setSelectedYear}',
'          months={months}',
'          years={years}',
'          departments={uniqueDepartments}',
'          selectedDepartment={selectedDepartment}',
'          setSelectedDepartment={setSelectedDepartment}',
'          selectedStatus={selectedStatus}',
'          setSelectedStatus={setSelectedStatus}',
'          role={user?.role}',
'        />',
'        )}',
'',
'        {/* Attendance Table */}',
'        {viewMode === "daily" && (',
'          <AttendanceTable ',
'            attendance={filteredAttendance}',
'            onViewDetails={handleViewDetails}',
'            onRegularize={(record) => {',
'              setRegData({ ...regData, date: record.date, type: ''Absent Correction'' });',
'              setShowRegModal(true);',
'            }}',
'            userRole={user?.role}',
'            loading={loading}',
'          />',
'        )}',
''
)

$finalContent = $before + $newLines + $after
$finalContent | Set-Content src/components/payroll/attendance-dashboard.jsx
